services:
  nexel.webapi:
    image: nexel.webapi
    build:
      context: .
      dockerfile: src/Nexel.WebAPI/Dockerfile
    ports:
      - "8080:8080"
    
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "8002:1433"
    
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: Y
    volumes:
      - sql-data:/var/opt/mssql
  
  unit_tests:
    image: "mcr.microsoft.com/dotnet/sdk:7.0"
    volumes:
      - ./tests:/tests
      - ./src:/src
    command:
      - /bin/bash
      - /tests/run_tests.sh

volumes:
  sql-data: